title: Purushottam Kumar
logo: 60935396_1718755354937741_1905648285968760832_o.jpg
description: A third year computer science undergraduate student at National Institute of Technology, Durgapur
theme: jekyll-theme-minimal
